swagger: "2.0"
info:
  title: "Chat Bot"
  version: "1.0.0"
host: "localhost:4009"
basePath: "/chat_bot/api/v1"
consumes:
- "application/json"
- "application/x-www-form-urlencoded"
produces:
- "application/json"
schemes:
- "http"
tags:
  - name: user
    description: "user api"
  - name: admin
    description: "admin api"
paths:
  "/user/login":
      post:
        summary: Authenticating user
        parameters: 
          - in: body
            name: user
            description: login user.
            required: true
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                    type: string
                password:
                    type: string
        responses:
          "200":
            description: Sucessfully login
            schema: 
              type: object
              properties:
                id: 
                  type: string
          "400":
            description: Please check your username/password and try again.

  "/connect/createFeed":
      post:
        summary: Creating new feeds.
        parameters:
        - name: "authorization"
          in: "header"
          required: true
          type: "string"
        - name: "body"
          in: "body"
          description: "connect details"
          required: true
          schema:
            $ref: "#/definitions/newFeeds"
        responses:
          "201":
            description: Sucessfully created feed.
            schema: 
              type: object
              properties:
                responseCode: 
                  type: number
                responseMessage: 
                  type: string
                roomId:
                  type: string
          "400":
            description: Access Forbidden.          
            schema: 
              type: object
              properties:
                responseCode: 
                  type: number
                responseMessage: 
                  type: string  
  "/connect/uploadFile":
      post:
        summary: Performing accept/reject function on notifications.
        parameters:
        - name: "authorization"
          in: "header"
          required: true
          type: "string"
        - name: "file"
          in: "formData"
          description: "file to upload"
          required: true
          type: "file"
        responses:
          "201":
            description: Sucessfully uploaded file.  
          "400":
            description: Failed to upload file.
                  
definitions:
  newFeeds:
    type: "object"
    required: 
    - "senderInfo"
    properties:
      senderInfo:
        type: "object"
        properties:
          fullName:
            type: "string"
          email:
            type: "string"
          id:
            type: "string"
      picture:
        type: "array"
        items:
          type: "string"
      content:
        type: "string"
        description: "This will contains the message you want to post."  
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
          